### ISSUE TITLE
Add support for newer versions of TfidfVectorizer attribute: get_feature_names_out

### ISSUE THREAD

**Issue by hazondata** [wjbmattingly/LeetTopic#10]
Lines 306, 314, 329 are using an older version of the attribute: get_feature_names

Newer sklearn versions uses get_feature_names_out

**Comment by wjbmattingly** [comment]
Thank you very much for this! This can easily be updated for 0.0.10.

**Comment by wjbmattingly** [comment]
This is now resolved with v. 0.0.10 which will go live shortly. Thanks again for identifying this!
